server:
  port: 8082

spring:
  application:
    name: fraud
  datasource:
    url: jdbc:postgresql://localhost:5433/fraud
    username: admin
    password: password
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQL10Dialect
        format_sql: true
    show-sql: true